fos_rest:
    param_fetcher_listener: force
    routing_loader:
        default_format: json
    view:
        view_response_listener: true
        templating_formats:
            html: false
    serializer:
        serialize_null: true
